"""Fix timestamp to posts

Revision ID: 9705ab5bcd32
Revises: 8a2f0e62d8b2
Create Date: 2024-07-25 18:14:03.952470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9705ab5bcd32"
down_revision: Union[str, None] = "8a2f0e62d8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
