"""Add is_offensive to commentaries

Revision ID: eeb8390253a3
Revises: 9705ab5bcd32
Create Date: 2024-07-25 18:15:50.111372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eeb8390253a3"
down_revision: Union[str, None] = "9705ab5bcd32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commentaries", sa.Column("is_offensive", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commentaries", "is_offensive")
    # ### end Alembic commands ###
