"""Add timestamp to posts

Revision ID: 8a2f0e62d8b2
Revises: 0127c29997bf
Create Date: 2024-07-25 18:13:20.975015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a2f0e62d8b2"
down_revision: Union[str, None] = "0127c29997bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "timestamp")
    # ### end Alembic commands ###
