"""add auto reponse options for post

Revision ID: c652d3f0683e
Revises: 3fd469e46233
Create Date: 2024-07-26 14:52:11.780128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c652d3f0683e"
down_revision: Union[str, None] = "3fd469e46233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "is_auto_response",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "response_threshold_in_seconds", sa.Integer(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "response_threshold_in_seconds")
    op.drop_column("posts", "is_auto_response")
    # ### end Alembic commands ###
